language: android

script: "./gradlew android:connectedLiteDebugAndroidTest
 -Pandroid.testInstrumentationRunnerArguments.class=bbct.android.lite.suite.GoodTests
  && ./gradlew android:connectedPremiumDebugAndroidTest
   -Pandroid.testInstrumentationRunnerArguments.class=bbct.android.premium.suite.GoodTests"

jdk:
    - oraclejdk8

android:
    components:
        - platform-tools
        - tools
        - build-tools-27.0.3
        - android-27

notifications:
    slack:
        secure: adVFUCFWI7SufxT76vDi94qWZz3c2Lk9DtJJA+JGXiL7lkNUELKA1ySkSINMtGy+UXKEQBwV6Ay2Iu65YkSYX9hvHsvAq8ohCyPecIgOtEPPGppZJUm6GKrx3monu47hb/I47SEN9DRkYUGT168jiLZVgIHhpVL45OsbpOhopw8=
